# Imagen base 
FROM node:18

# Carpeta dentro del contenedor
WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el proyecto in incluyendo todos los archivos de código
COPY . .

# Puerto en el cual va a correr el front
EXPOSE 5173

# Ejecutar Vite en modo desarrollo
CMD ["npm", "run", "dev", "--", "--host"]